apiVersion: apps/v1
kind: Deployment
metadata:
    name: shinobi-war-fairy-main
    namespace: default
    labels:
        app: shinobi-war-fairy-main
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shinobi-war-fairy-main
    template:
        metadata:
            labels:
                app: shinobi-war-fairy-main
            annotations:
                dapr.io/enabled: 'true'
                dapr.io/app-id: 'main'
                dapr.io/app-port: '3000'
        spec:
            containers:
                - name: shinobi-war-fairy-main
                  image: registry.digitalocean.com/sw-fairy-k8s/sw-fairy-k8s-main:{{commitId}}
                  ports:
                      - containerPort: 3000
                        name: http
