version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0
  docker: circleci/docker@1.6.0

jobs:
  deploy:
    docker:
      - image: circleci/node:7.10
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - kubernetes/install-kubectl
      - run: docker build . --tag sw-fairy-k8s-main:init1
      - run: docker login -u $sw_fairy_api_token -p $sw_fairy_api_token registry.digitalocean.com
      - run: docker tag sw-fairy-k8s-main:init1 registry.digitalocean.com/sw-fairy-k8s/sw-fairy-k8s-main:init1
      - run: docker push registry.digitalocean.com/sw-fairy-k8s/sw-fairy-k8s-main:init1
      - run: kubectl --kubeconfig=/dev/null --server=https://9766b21f-9055-436e-a20a-8018422119a5.k8s.ondigitalocean.com --insecure-skip-tls-verify --token=$sw_fairy_k8s_token apply -f ./k8s/

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context:
            - Shinobi War Fairy
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - main
