version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0
  docker: circleci/docker@1.6.0

jobs:
  deploy:
    docker:
      - image: circleci/node:7.10
    executor: docker/docker
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: docker build . --tag sw-fairy-k8s-main:init0
      - run: docker login -u $sw_fairy_api_token -p $sw_fairy_api_token
      - run: docker tag sw-fairy-k8s-main:init0 registry.digitalocean.com/sw-fairy-k8s/sw-fairy-k8s-main:init0
      - run: docker push registry.digitalocean.com/sw-fairy-k8s/sw-fairy-k8s-main:init0

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context:
            - Shinobi War Fairy
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - main
