version: 2.1

orbs:
    kubernetes: circleci/kubernetes@0.12.0
    docker: circleci/docker@1.6.0

jobs:
    deploy:
        docker:
            - image: cimg/node:16.7.0
        executor: docker/docker
        steps:
            - setup_remote_docker
            - checkout
            - kubernetes/install-kubectl
            - run: sudo npm i gulp-cli @massfice/sw-fairy-common-deploy-scripts typescript ts-node -g
            - run: gulp deploy --commit $CIRCLE_SHA1 --dtoken $DOCKER_TOKEN --ktoken $KUBE_TOKEN
workflows:
    version: 2
    deploy:
        jobs:
            - deploy:
                  context:
                      - Shinobi War Fairy
                  filters:
                      branches:
                          only:
                              - main
