version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: kubectl --version

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - main
